[phases.setup]
nixPkgs = [
    "python310",
    "nodejs-18_x",
    "nginx",
    "gcc",
    "pkg-config",
    "openssl",
    "libffi",
    "libxml2",
    "libxslt",
    "icu"
]

[phases.install]
cmds = [
    "python3.10 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install uv",
    "uv sync --python 3.10 --frozen"
]

[phases.build]
cmds = [
    "cd web && npm install && npm run build",
    "chmod +x ../docker/entrypoint.sh"
]

[start]
cmd = """
mkdir -p /app/conf
if [ ! -f /app/conf/service_conf.yaml ]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
        eval "echo \"$line\"" >> /app/conf/service_conf.yaml
    done < /app/conf/service_conf.yaml.template
fi
./docker/entrypoint.sh
"""

[variables]
PYTHONPATH = "/app"
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/"
PATH = "/opt/venv/bin:$PATH"